# Generated by Django 4.0.1 on 2022-01-27 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_dependents_dental_plan_dependents_health_plan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='title',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='employees.hierarchy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeaddress',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='flex_work_hours',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='free_dressing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='gympass',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='pl',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='snack_break',
            field=models.BooleanField(default=True),
        ),
    ]
