# Generated by Django 4.0.1 on 2022-01-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employees_title_alter_employeeaddress_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaddress',
            name='complement',
            field=models.TextField(default='Condominio Village Do Bosque I, bl.04 ap.07'),
            preserve_default=False,
        ),
    ]
