# Generated by Django 4.0.1 on 2022-01-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_dependents_active_dependents_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dependents',
        ),
    ]
