# Generated by Django 4.0.1 on 2022-01-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_delete_dependents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=80)),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('active', models.BooleanField(default=True)),
                ('relationship', models.CharField(max_length=25)),
                ('health_plan_number', models.CharField(max_length=12)),
                ('dental_plan', models.CharField(max_length=12)),
                ('life_insurance', models.CharField(max_length=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
            options={
                'db_table': 'dependents',
            },
        ),
    ]
