# Generated by Django 4.0.1 on 2022-01-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_dependents'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='bank_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
